name: waterbalans
channels:
  - defaults
dependencies:
  - python=3.7
  - geopandas
  - jupyter
  - jupyterlab
  - numpy
  - pandas=0.25.0
  - pip
  - scipy
  - shapely
  - tqdm
  - xlrd
  - pip:
    - descartes

  
  - pip:
    - hkvfewspy==0.6.2
    - pastas==0.17.0
    - requests
    - zeep
