name: waterbalans
channels:
  - defaults
dependencies:
  - python=3.7
  - geopandas
  - jupyter
  - jupyterlab
  - numpy
  - pandas=1.3.0
  - pip
  - scipy
  - shapely
  - tqdm
  - xlrd
  - pip:
    - descartes
    - dateparser
    - hkvfewspy==0.6.2
    - requests
    - zeep
