name: waterbalans
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - pip
  - scipy
  - shapely
  - tqdm
  - xlrd
  - openpyxl
  - pyogrio
  - pip:
    - descartes
    - dateparser
    - hkvfewspy==0.6.2
    - requests
    - zeep
    - pastas
